### ISSUE TITLE
Does not work with the latest cucumber version (0.10.2)

### ISSUE THREAD

**Issue by Dunkelheit** [icemobilelab/minosse#46]
Hello team,

Using the latest `cucumber` version, `0.10.2`, throws the following error:
```
a.martinezminguez in ~/Projects/Jumbo/jumbo-api-integration on master*
🍕  gulp integration
[14:16:02] Using gulpfile ~/Projects/Jumbo/jumbo-api-integration/gulpfile.js
[14:16:02] Starting 'integration'...
Feature: As a user I want to get my auto complete list

/Users/a.martinezminguez/Projects/Jumbo/jumbo-api-integration/node_modules/minosse/lib/steps.js:8
        done();
        ^

TypeError: done is not a function
    at new World (/Users/a.martinezminguez/Projects/Jumbo/jumbo-api-integration/node_modules/minosse/lib/steps.js:8:9)
[14:16:03] 'integration' errored after 964 ms
[14:16:03] Error: Command `./node_modules/cucumber/bin/cucumber.js features/**/*.feature -r steps/*.js -f pretty` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)
```

This does not occur with version `0.7.0`.

It might be an idea to update `minosse` so that is able to work with the latest `cucumber` version, or at least warn the users in the README.md file.
